In [47]:
from sklearn.datasets import load_iris

In [48]:
iris_dataset = load_iris()

In [49]:
print("keys of iris dataset: \n{}".format(iris_dataset.keys()))

keys of iris dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [50]:
print(iris_dataset['DESCR'][:193]+"\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


In [51]:
print("target names: {}".format(iris_dataset['target']))

target names: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [52]:
print(" target_names names: {}".format(iris_dataset['target_names']))

 target_names names: ['setosa' 'versicolor' 'virginica']


In [53]:
print("feature names : {}".format(iris_dataset['feature_names']))

feature names : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [54]:
print("file names : {}".format(iris_dataset['filename']))

file names : C:\ProgramData\Anaconda3\lib\site-packages\sklearn\datasets\data\iris.csv


In [55]:
print("type of data: {}".format(type(iris_dataset['data'])))

type of data: <class 'numpy.ndarray'>


In [56]:
print("shape of data: {}".format(iris_dataset['data'].shape))

shape of data: (150, 4)


In [59]:
print("First five column of the dataset: \n{}".format(iris_dataset['data'][:5]))

First five column of the dataset: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
